# Project: CovidSurvival
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Sources/dirent.o Sources/filesManagement.o Sources/game.o Sources/generic.o Sources/link.o Sources/main.o
LINKOBJ  = Sources/dirent.o Sources/filesManagement.o Sources/game.o Sources/generic.o Sources/link.o Sources/main.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = CovidSurvival.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Sources/dirent.o: Sources/dirent.c
	$(CC) -c Sources/dirent.c -o Sources/dirent.o $(CFLAGS)

Sources/filesManagement.o: Sources/filesManagement.c
	$(CC) -c Sources/filesManagement.c -o Sources/filesManagement.o $(CFLAGS)

Sources/game.o: Sources/game.c
	$(CC) -c Sources/game.c -o Sources/game.o $(CFLAGS)

Sources/generic.o: Sources/generic.c
	$(CC) -c Sources/generic.c -o Sources/generic.o $(CFLAGS)

Sources/link.o: Sources/link.c
	$(CC) -c Sources/link.c -o Sources/link.o $(CFLAGS)

Sources/main.o: Sources/main.c
	$(CC) -c Sources/main.c -o Sources/main.o $(CFLAGS)
